### PR TITLE
Fix spider middleware yielding requests twice

### PR DESCRIPTION
**Pull request by HarrisonGregg**
This bug currently causes a duplicate request warning message whenever a request that doesn't include `depth` in `request.meta` is also allowed by the filters.  When `request.dont_filter=True` is used, the bug causes `KeyError`s that prevent the spider from functioning.  This change fixes both problems.

### CODE REVIEW

**Comment by HarrisonGregg** [comment]
@wearpants Any comments before I merge this?

**Comment by wearpants** [comment]
Will look today or tomorrow

**Comment by wearpants** [comment]
This is a really good catch! I'd prefer the fix be written as an nested if-else than a continue though, i think that'll make it clearer what's going on.

**Comment by HarrisonGregg** [comment]
For the record, @jodizzle found it.  I had looked for the cause of these problems before, but couldn't find it.

I wasn't sure whether to go for minimal changes, or to refactor for clarity while I was in there.  I've refactored a little and added comments to make it more explicit what's going on.

**Comment by HarrisonGregg** [comment]
@wearpants How does it look now?

**Comment by wearpants** [comment]
This is awesome. :-) :-) :-)

Much clearer than the original version - the bug just drops right out. Nice.

**Pull request merged**
